apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: worker
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: worker
    spec:
      volumes:
      - name: google-cloud-key
        secret:
          secretName: worker-key
      containers:
      - name: worker
        image: eu.gcr.io/college-de-france/worker
        volumeMounts:
        - name: google-cloud-key
          mountPath: /var/secrets/google
        env:
        - name: GET_HOSTS_FROM
          value: dns
        - name: GOOGLE_APPLICATION_CREDENTIALS
          value: /var/secrets/google/key.json
        command: ["go-wrapper"]
        args: ["run", "--project_id=college-de-france", "--bucket=healthy-cycle-9484", "--sox_path=sox", "--elastic_address=http://elasticsearch:9200"]
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: elasticsearch
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: elasticsearch
    spec:
      securityContext:
        # Same group as elastic user at to be able to read/write the mounted volume.
        fsGroup: 1000
      initContainers:
        - name: init-sysctl
          image: busybox
          imagePullPolicy: IfNotPresent
          command: ["sysctl", "-w", "vm.max_map_count=262144"]
          securityContext:
            privileged: true
      volumes:
        - name: es-persistent-storage
          gcePersistentDisk:
            pdName: es-disk
            fsType: ext4
      containers:
      - name: elasticsearch
        image: docker.elastic.co/elasticsearch/elasticsearch:5.5.2
        command: ["bin/elasticsearch"]
        args: ["-Expack.security.enabled=false", "-Ecluster.name=esdb", "-Enode.name=master-data-node", "-Enetwork.host=0.0.0.0", "-Ebootstrap.memory_lock=true", "-Ediscovery.zen.minimum_master_nodes=1", "-Ediscovery.type=single-node"]
        securityContext:
          capabilities:
            add:
              - IPC_LOCK
        ports:
        - containerPort: 9200
          name: http
          protocol: TCP
        volumeMounts:
        - mountPath: /var/data/elasticsearch
          name: es-persistent-storage
